services:
  - type: web
    name: atm-interface
    env: python
    region: singapore  # Choose the region closest to your users
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python init_db.py
      gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: MYSQL_HOST
        fromDatabase:
          name: atm-db
          property: host
      - key: MYSQL_USER
        fromDatabase:
          name: atm-db
          property: user
      - key: MYSQL_PASSWORD
        fromDatabase:
          name: atm-db
          property: password
      - key: MYSQL_DATABASE
        value: atm_db
      - key: MYSQL_PORT
        value: 3306

databases:
  - name: atm-db
    databaseName: atm_db
    user: atm_user
    plan: free